Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs
Shipcontrol had a wrongly named collision callback so it wasn't getting called.
=> fix: fix naming of OnCollisionEnterCallback

Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs
Fixes a bug where the friction VFX which gets played when the player takes damage would only be played on the server. This also showcases the new NetworkTime feature.
Fixes #13
=> fix: spaceshooter hit vfx

.yamato/build.yml
Add external triggers which check that bitesize develop projects still compile with latest NGO develop
=> chore: Add external ngo develop branch triggers

Basic/Invaders/Assets/Prefabs/player.prefab, Basic/Invaders/Assets/Scripts/InvadersGame.cs, Basic/Invaders/Assets/Scripts/MenuControl.cs, Basic/Invaders/Assets/Scripts/PlayerControl.cs, Basic/Invaders/Assets/Scripts/SceneTransitionHandler.cs
This PR fixes how player color is set so that it is set for late-joining players too. It also simplifies how the scene transition callbacks are setup and adds an RPC call to replicate the timer for late-joining players.
Fixes #28
=> fix: invaders late join issues

Basic/Invaders/Assets/Scripts/InvadersGame.cs
A call happening on the client to get its player object used a property that is only available to the server. This resulted in a NotServerException. This PR fixes this issue by instead using a property available on the client.
=> fix: fixing NotServerException [MTT-4029]

Basic/ClientDriven/Packages/manifest.json, Basic/ClientDriven/Packages/packages-lock.json, Basic/ClientDriven/ProjectSettings/ProjectVersion.txt
Quick PR to update ClientDriven sample to the latest LTS version (2021.3.12f1).
=> chore: ClientDriven LTS update to 2021.3.12f1

Basic/ClientDriven/Assets/Scripts/ServerIngredientSpawner.cs
Quick fix PR to offset ingredient spawns to prevent stacking.
=> fix: ingredient spawn position offset

Basic/2DSpaceShooter/Packages/manifest.json, Basic/2DSpaceShooter/Packages/packages-lock.json, Basic/Invaders/Packages/manifest.json, Basic/Invaders/Packages/packages-lock.json, CHANGELOG.md
This PR updates the Invaders and 2DSpaceShooter sample to Netcode for GameObjects v1.2.0.
=> feat: updating Invaders and 2DSpaceShooter to Netcode for GameObjects v1.2.0

Basic/ClientDriven/Assets/Prefabs/PlayerArmature_Networked.prefab, Basic/ClientDriven/Assets/Scripts/ClientPlayerMove.cs, Basic/ClientDriven/Assets/Scripts/ServerPlayerMove.cs, CHANGELOG.md
PR that includes a better flow for synchronizing initial position on clients that isn't dependent on ClientRpcs. The position of owning clients is still set server-side, and it guarantees no race conditions with CharacterController's initialization.
=> fix: ClientDriven initial position sync fix on owning clients

Basic/2DSpaceShooter/Assets/Fonts/chintzy SDF.asset
Updated font asset to have correct Unicode hex for the underline character--this stops a couple of warnings from being spammed in the console
```
The character used for Underline is not available in font asset [chintzy SDF].
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```
and 
```
The character used for Underline is not available in font asset [chintzy SDF].
UnityEngine.UIElements.UIElementsRuntimeUtilityNative:UpdateRuntimePanels ()
```
[Jira ticket [MTT-5223] here](https://jira.unity3d.com/browse/MTT-5223)
=> Fix: Broken Reference for Underline Character in Font Asset (2D Space Shooter) [MTT-5223]

Basic/2DSpaceShooter/Assets/Prefabs/Bullet.prefab, Basic/2DSpaceShooter/Assets/Scripts/Bullet.cs, Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs, CHANGELOG.md
Because of NetworkTransform's interpolation, the bullets' explosion vfx were happening too early on clients. This PR fixes this by removing the NetworkTransform entirely. Bullets are now spawned and initialized on the server and clients handle their movement locally. Collision detection still happens only on the server. The result is that bullets' positions are no longer synchronized and interpolated. It is thus possible that a small desync happens during a bullet's lifetime, but since it is quite short it wouldn't cause issues. Plus, it would only be a visual artifact since all gameplay logic is still server-driven.
[MTT-5080](https://jira.unity3d.com/browse/MTT-5080)
=> fix: bullet explosion desync [MTT-5080]

Basic/2DSpaceShooter/Assets/Scripts/Spawner.cs, CHANGELOG.md
This simply moves the update to the powerups' `buffType` NetworkVariable to after they are spawned to remove the warnings in the console.
None
=> fix: removing warning when spawning powerups

Basic/DynamicAddressablesNetworkPrefabs/Assets/Prefabs/UI.prefab, Basic/DynamicAddressablesNetworkPrefabs/Assets/Prefabs/UI.prefab.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/UI.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/UI/IPMenuUI.cs, Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/UI/IPMenuUI.cs.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/UI/InGameUI.cs, Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/UI/InGameUI.cs.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/PanelSettings.asset, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/PanelSettings.asset.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/Template_ConnectionUI.uxml, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/Template_ConnectionUI.uxml.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/Template_PrefabRow.uxml, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/Template_PrefabRow.uxml.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_ConnectionType.uxml, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_ConnectionType.uxml.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_ConnectionUIHolder.uxml, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_ConnectionUIHolder.uxml.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_IPMenu.uxml, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_IPMenu.uxml.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_InGameUI.uxml, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UI_InGameUI.uxml.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/USS_Clients.uss, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/USS_Clients.uss.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/USS_StyleSheet.uss, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/USS_StyleSheet.uss.meta, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UnityDefaultRuntimeTheme.tss, Basic/DynamicAddressablesNetworkPrefabs/Assets/UI/UnityDefaultRuntimeTheme.tss.meta
This is a new branch for the UI toolkit work I've been doing in [PR #92](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/pull/92) to avoid merge/filepath issues after the project folder was renamed. My UI work was purely additive at this point, so I extracted it as a unity package and added back into this branch, which is based off of develop.
Here is the copied description from that PR, with the only visual change being that the Reset Scene button has since been removed:
> This is a PR for the implementation of UI toolkit for the dynamic prefabs sample. The old UI has been converted over to UI toolkit elements, and new elements to support the added functionality of the sample have been added as well. The functionality of the UI is pretty limited--this is …
=> Feat: Dynamic Prefabs UIToolkit UI (Post Project Rename) [MTT-5427]

Basic/DynamicAddressablesNetworkPrefabs/README.md
Added this little bit to the readme to address one PR comment that was missed
=> Feat: Last readme update for release

Basic/2DSpaceShooter/ProjectSettings/ProjectSettings.asset, Basic/2DSpaceShooter/README.md, Basic/ClientDriven/ProjectSettings/ProjectSettings.asset, Basic/ClientDriven/README.md, Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/ProjectSettings.asset, Basic/DynamicAddressablesNetworkPrefabs/README.md, Basic/Invaders/ProjectSettings/ProjectSettings.asset, Basic/Invaders/README.md, CHANGELOG.md, README.md
fixed some broken readme links, added in direct links to each sample's documentation page from their respective readmes, updated project versions to new patch, and updated changelog
=> Minor fixes for the 1.2.1 patch

README.md
Readme language updates and fixed broken links
=> Feat: Readme updates 1.2.1

Basic/Invaders/Assets/Scenes/StartMenu.unity, Basic/Invaders/Assets/Scripts/MenuControl.cs, CHANGELOG.md
[style guide]: https://unity-docs.gitbook.io/style-guide/
[release note guide lines]: https://unity-docs.gitbook.io/style-guide/style/release-notes
[coding conventions]: https://github.cds.internal.unity3d.com/unity/unity-meta/blob/stable/ReferenceSource/CSharp/Assets/CSharpReference.cs
Invaders didn't previously allow for passing in the IP address' input field text value into UTP's connection data and only allowed local hosting (127.0.0.1). This PR adds that functionality to the Invaders sample, allowing the ability to connect to a remote IP address.
- Windows, 2021.3.18f1
- N/A
- Remember to familiarize yourself with the [coding conventions]
1. Clone this branch
2. Open it with the aforementioned Unity version
3. Create a build.
4. Host and set public IP for the connect address.
5. Have …
=> fix: applying address inside TMP field to UTP connection data as host

Basic/2DSpaceShooter/Packages/manifest.json, Basic/2DSpaceShooter/Packages/packages-lock.json, Basic/ClientDriven/Assets/Prefabs/PlayerArmature_Networked.prefab, Basic/ClientDriven/Packages/manifest.json, Basic/ClientDriven/Packages/packages-lock.json, Basic/Invaders/Packages/manifest.json, Basic/Invaders/Packages/packages-lock.json, CHANGELOG.md
PR to upgrade all bitesize samples that were referencing Samples Utilities package to now point to a specific version, and will do so in the future.
N/A
=> fix: 2DSpaceShooter, ClientDriven, & Invaders point to v2.2.0 Samples Utilities package

Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/05_API Playground/APIPlayground.cs, CHANGELOG.md
This PR fixes the "Loading" state being displayed inside the API Playground scene when the host hits the Spawn 
[MTT-6688](https://jira.unity3d.com/browse/MTT-6688)
Repro steps:
* Open scene 05_API Playground Showcasing All Post-Connection Use-Cases
* Hit play
* Host
* Hit Try Spawn Synchronously button
* Observe that the loading state of the loading prefab transitions from Loading to Loaded (this can happen quickly), but does not get stuck on Loading.
This was reproduceable on just the host, but testing the same steps with a ParrelSync client connected would be appreciated for sanity's sake.
=> fix: DynamicAddressablesNetworkPrefabs showing loading status on already spawned prefabs [MTT-6688]

Basic/ClientDriven/Assets/Prefabs/Ingredient.prefab, Basic/ClientDriven/Assets/Prefabs/PlayerArmature_Networked.prefab, Basic/ClientDriven/Assets/Scenes/Bootstrap.unity, Basic/ClientDriven/Assets/Scripts/DebugSimulationSlider.cs, Basic/ClientDriven/Assets/Scripts/ServerIngredient.cs, Basic/ClientDriven/Assets/Scripts/ServerPlayerMove.cs
Fixes several issues:
- Picking up now handles parenting slightly different where object is scaled and the visual is parented under a skeleton based GameObject.
- Tossing the ball now actually "tosses the ball".
- Debug simulation sliders no longer show up on clients when connected to a session.
- Other minor tweaks related to these adjustments.
- Updating the ingredient prefab and fixing an issue with player despawning server-side with ingredient still being held.
=> fix: general fixes and client-side debug simulation tool fix

Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs, CHANGELOG.md
This is an internal PR that brings along the fix completed in this external PR.
Yamato jobs won't trigger from external PRs, so this is a temporary solution to ensure jobs run on external work.
Here, variable names are swapped for proper initialization.
N/A. Original PR: #145 
=> fix: correct variable names used for initialization (external PR #145)

Basic/2DSpaceShooter/Assets/Prefabs/Ship.prefab, Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs, CHANGELOG.md
Addressing the issue [here](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/issues/128).
This PR removes an unnecessary NetworkVariable from 2DSpaceShooter.
Benefit: reducing network bandwidth used to sync variable to clients.
Original [issue](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/issues/128).
=> fix: remove unnecessary NetworkVariable in 2DSpaceShooter

Experimental/MultiplayerUseCases/Assets/Editor/Tutorials/NetworkVariablesVsRPC/50-TestNetworkBehaviour.asset
The last page of the Data and event synchronization tutorial of MultiplayerUseCases sample tells the user that they can use ParrelSync, but the ParrelSync window was not interactable due to IET masking.
The masking settings of that tutorial page were adjusted so that users can use the ParrelSync window in the last step of the tutorial.
[MTT-7858](https://jira.unity3d.com/browse/MTT-7858)
=> MTT-7858: Make ParrelSync window interactable in tutorial

Basic/ClientDriven/Assets/Prefabs/Ingredient.prefab, Basic/ClientDriven/Assets/Prefabs/PlayerArmature_Networked.prefab, Basic/ClientDriven/Assets/Scripts/ClientDrivenNetworkTransform.cs, Basic/ClientDriven/Assets/Scripts/ClientDrivenNetworkTransform.cs.meta, Basic/ClientDriven/Assets/Scripts/ClientPlayerMove.cs, Basic/ClientDriven/Assets/Scripts/ServerPlayerMove.cs, Basic/ClientDriven/Packages/manifest.json, Basic/ClientDriven/Packages/packages-lock.json, CHANGELOG.md
This PR upgrades the project to Netcode for GameObjects v1.8.1. Along with that comes:
* upgrade to Universal Rpcs (only in 2 locations)
* place of execution for client's position was moved to ClientNetworkTransform child class, ClientDrivenNetworkTransform, to ensure no race condition issues on first position sync
* Server code now modifies a NetworkVariable that now client-owned instances of ClientDrivenNetworkTransform use on OnNetworkSpawn to initially move a player
How to test:
* Host on editor/build
* Join 3 client instances (editor/build)
* Validate that the 4th joining client would simply be spawned at the origin AND that there aren't any position discrepancies on client vs host
[MTT-7985](https://jira.unity3d.com/browse/MTT-7985)
- [ N/A ] Tests have been added for the project …
=> feat: ClientDriven upgrade to Netcode for GameObjects v1.8.1, client position place of execution change, Universal Rpc upgrade [MTT-7985]

Basic/ClientDriven/Assets/Scripts/ServerIngredientPhysics.cs
This PR removes the SetPhysics method from ServerIngredientPhysics and is adding comments to the changes made to the Rigidbody variables to make the intent easier to understand.
[MTT-8377](https://jira.unity3d.com/browse/MTT-8377) Adding a comment on why Rigidbody.interpolation need to be changed on kinematic objects when parenting them.
=> Fix: Adding comments on ingredients parenting to make it clear what is being done [MTT-8377]

Basic/Invaders/Packages/manifest.json, Basic/Invaders/Packages/packages-lock.json, Basic/Invaders/ProjectSettings/ProjectVersion.txt, Basic/Invaders/UserSettings/EditorUserSettings.asset, CHANGELOG.md
Upgraded the project to the latest LTS.
Run the project locally with a host and a client to make sure the gameloop was still working without errors.
[MTT-8505](https://jira.unity3d.com/browse/MTT-8505) - Upgraded Invaders Sample to Unity 2022.3.27f1
=> Upgrade Invaders Sample to Unity 2022.3.27f1 [MTT-8505]

Basic/2DSpaceShooter/Packages/packages-lock.json, Basic/2DSpaceShooter/ProjectSettings/ProjectVersion.txt, CHANGELOG.md
Upgraded 2D Space Shooter to the latest LTS (2022.3.27f1).
Run the project locally with a host and a client to make sure the game loop is still working without any errors.
[MTT-8500](https://jira.unity3d.com/browse/MTT-8500)
=> Upgrade 2D Space Shooter to Unity Editor 2022.3.27f1 [MTT-8500]

Basic/DynamicAddressablesNetworkPrefabs/Packages/packages-lock.json, Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/ProjectVersion.txt, CHANGELOG.md
PR to upgrade DynamicAddressablesNetworkPrefabs to Unity 2022.3.27f1 LTS.
[MTT-8513](https://jira.unity3d.com/browse/MTT-8513)
=> feat: DynamicAddressablesNetworkPrefabs upgraded to 2022.3.27f1 [MTT-8513]

Basic/2DSpaceShooter/Assets/Scripts/Bullet.cs, Basic/2DSpaceShooter/Assets/Scripts/NetworkManagerHud.cs, Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs, Basic/2DSpaceShooter/Packages/manifest.json, Basic/2DSpaceShooter/Packages/packages-lock.json, CHANGELOG.md
Upgraded 2D Space Shooter to NGO 1.8.1 
- added the new Rpc attribute
- added OnConnectionEvent
I DID NOT add the new `InstantiateAndSpawn ` to it yet. I tried to add it to the `Spawner.cs` script, but it did not work well due to a NetworkObjectPool being used
e.g. `GameObject go = m_ObjectPool.GetNetworkObject(m_AsteroidPrefab.gameObject); ` does not work. I am not sure if I should include InstantiateAndSpawn here?
[MTT-8498](https://jira.unity3d.com/browse/MTT-8498)
=> Feature: Upgrading 2D Space Shooter to NGO 1.8.1 [MTT-8498]

Basic/DynamicAddressablesNetworkPrefabs/Assets/Scripts/00_Preloading/Preloading.cs, CHANGELOG.md
A bug was discovered when testing Preloading scene where the Dynamic Prefab loading in Preloading scene was null, due to the Addressables handle being released as soon as the prefab was loaded.
The Release call was moved to this MonoBehaviour's OnDestroy method.
N/A
To Test:
Load 00_Preloading Dynamic Prefabs scene.
Host on one instance.
See that the warnings shared below don't appear on console.
Verify that the same is for a joining client.
=> fix: releasing Addressables handle on OnDestroy in DynamicAddressablesNetworkPrefabs Preloading scene

.yamato/2DSpaceShooter_triggers.yml, .yamato/ClientDriven_triggers.yml, .yamato/DedicatedGameServer_triggers.yml, .yamato/MultiplayerUseCases_triggers.yml, .yamato/dynamicaddressablesnetworkprefabs_triggers.yml, .yamato/shared_triggers.yml
=> mtt-8638-Separate-PR-Triggers-per-project

Experimental/MultiplayerUseCases/Assets/Editor/Tutorials/NetworkVariables/CompletionDialog.asset, Experimental/MultiplayerUseCases/Assets/Editor/Tutorials/NetworkVariablesVsRPC/40-InspectTheCube2.asset, Experimental/MultiplayerUseCases/Assets/Editor/Tutorials/NetworkVariablesVsRPC/CompletionDialog.asset, Experimental/MultiplayerUseCases/Assets/Editor/Tutorials/ProximityChecks/CompletionDialog.asset, Experimental/MultiplayerUseCases/Assets/Editor/Tutorials/RPCs/CompletionDialog.asset, Experimental/MultiplayerUseCases/Assets/UseCaseSamples/NetvarVsRpc/NetvarVsRPC.unity, Experimental/MultiplayerUseCases/README.md
Addressed design feedback posted [here](https://www.figma.com/board/0snKTg9Hz59WKP6VFOlsVp/Samples-Audit?node-id=26-63&t=Gyo3dNaPUq0R5TCq-0)
- https://jira.unity3d.com/browse/MTT-7498
=> Usecases design feedback for out-of-experimental release (MTT-7498)

Experimental/DistributedAuthoritySample/Assets/Shaders/Toon.shadergraph
FORWARD_PLUS define enables some feature in MacOS Arm that breaks the build. This will be fixed within upcoming Unity Versions, in the meantime we remove the Define.
[MTT-9228](https://jira.unity3d.com/browse/MTT-9228)
=> fix: Remove shader define FORWARD_PLUS

Experimental/DistributedAuthoritySample/Assets/Scripts/UI/IngameUI/UIUtils.cs
World2Screenpoint returns a valid ScreenPosition even if the Worldpoint is behind the camera. Adds a check to move the VisualElement out of the Viewport if the Player is behind the camera.
[MTTB-548]https://jira.unity3d.com/browse/MTTB-548
Issue:
=> [DistributedAuthoritySample]  MTTB-548 Hide Player Names if they are behind the camera.

Experimental/DistributedAuthoritySample/Assets/Prefabs/Gameplay/InGameHandler.prefab, Experimental/DistributedAuthoritySample/Assets/Prefabs/Gameplay/InGameHandler.prefab.meta, Experimental/DistributedAuthoritySample/Assets/Prefabs/Gameplay/MainMenuHandler.prefab, Experimental/DistributedAuthoritySample/Assets/Prefabs/Gameplay/MainMenuHandler.prefab.meta, Experimental/DistributedAuthoritySample/Assets/Scenes/MainMenu.unity, Experimental/DistributedAuthoritySample/Assets/Scripts/GameManagement/GameplayEventHandler.cs, Experimental/DistributedAuthoritySample/Assets/Scripts/GameManagement/InGameHandler.cs, Experimental/DistributedAuthoritySample/Assets/Scripts/GameManagement/InGameHandler.cs.meta, Experimental/DistributedAuthoritySample/Assets/Scripts/GameManagement/MainMenuHandler.cs, Experimental/DistributedAuthoritySample/Assets/Scripts/GameManagement/MainMenuHandler.cs.meta, Experimental/DistributedAuthoritySample/Assets/Scripts/Services/ServicesHelper.cs, Experimental/DistributedAuthoritySample/Assets/Scripts/Services/Unity.Multiplayer.Samples.SocialHub.Services.asmdef
This PR adds a listener the game scene to return to the main menu if a session is left/disconnected or a client is removed from said session. 
[MTTB-551](https://jira.unity3d.com/browse/MTTB-551)
=> fix: Distributed Authority Sample - listening to session exited callback to return to main menu [MTTB-551]

Experimental/DistributedAuthoritySample/Assets/Art/Characters/PigChef/Animation/PigChef.controller, Experimental/DistributedAuthoritySample/Assets/Scripts/Player/AvatarInteractions.cs
This PR enables the throwing animation to transition to the drop state.
This fixes the issue seen when a player is stuck in a throwing animation when a pot/crate is transferred or destroyed.
Technically the game was trying to transition the player back to the drop state, but the animator didn't allow that transition, since there wasn't one.
[MTTB-543](https://jira.unity3d.com/browse/MTTB-543)
=> fix: Distributed Authority Sample - animation transition from throwing to drop [MTTB-543]

.yamato/project.metafile, Basic/DynamicAddressablesNetworkPrefabs/Assets/AddressableAssetsData/AssetGroups/Built In Data.asset, Basic/DynamicAddressablesNetworkPrefabs/Packages/manifest.json, Basic/DynamicAddressablesNetworkPrefabs/Packages/packages-lock.json, Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/MultiplayerManager.asset, Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/ProjectVersion.txt, Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/VirtualProjectsConfig.json, Basic/DynamicAddressablesNetworkPrefabs/README.md, CHANGELOG.md, README.md
This PR upgrades Dynamic Addressables Network Prefabs to Unity 6 and upgrades associated dependencies.
Netcode for GameObjects has been upgraded to v2.2.0.
ParrelSync has been removed from the project and Multiplayer Play Mode has been integrated.
N/A
=> feat: Dynamic Addressables Network Prefabs - upgrade to 6000.0.34f1 LTS & NGO v2.2.0

.yamato/build.yml, .yamato/tests.yml
Quick PR to fix the jobs failing [here](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/pull/281). The way Unity Downloader CLI is fetched is now the recommended API.
N/A
=> fix: changes to unity cli source api fetching
