Unity-Technologies/com.unity.multiplayer.samples.bitesize

README.md

Updated the README:
- New doc link 
- Removed open source, updated contributing section

update: README new doc link and remove open source

---

Basic/2DSpaceShooter/Assets/Prefabs/Ship.prefab
Basic/2DSpaceShooter/Assets/Scenes/network.unity
Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs
CHANGELOG.md

Co-authored-by: Cosmin <38663153+Cosmin-B@users.noreply.github.com>

chore: merge main back into develop

---

Basic/ClientDriven/Assets/Scenes/Bootstrap.unity
Basic/ClientDriven/Assets/Scripts/BootstrapManager.cs

This PR replaces the usage of OnGUI for connection establishment with UI buttons placed on the canvas.

refactor: changed ClientDriven connection UI to use UI buttons and events instead of OnGUI [MTT-4201]

---

Basic/ClientDriven/Assets/URP/UniversalRenderPipelineAsset.asset
Basic/ClientDriven/ProjectSettings/QualitySettings.asset

Switched on anti aliasing (MSAA 4x) in the URP settings

Feat: Client Driven Anti Aliasing

---

CHANGELOG.md

Date change for v.1.1.0 release on the changelog.

chore: changelog update for v1.1.0 release

---

.yamato/project.metafile

Quick PR to add ClientDriven to the suite of project tests.
No issue number.

feat: adding ClientDriven to project metafile for yamato testing

---

CHANGELOG.md

added missing pr to changelog (#87)

Feat: added missing pr to changelog

---

CHANGELOG.md

one last final readme update added to the changelog :)

one last final readme update added to the changelog :)

---

CHANGELOG.md

Added a missing PR link to the changelog

Feat: Changelog update

---

Basic/2DSpaceShooter/ProjectSettings/ProjectSettings.asset
Basic/2DSpaceShooter/README.md
Basic/ClientDriven/ProjectSettings/ProjectSettings.asset
Basic/ClientDriven/README.md
Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/ProjectSettings.asset
Basic/DynamicAddressablesNetworkPrefabs/README.md
Basic/Invaders/ProjectSettings/ProjectSettings.asset
Basic/Invaders/README.md
CHANGELOG.md
README.md

v1.2.1 Updates: Fixed broken readme links, added in direct links to each sample from their respective readmes, updated project versions to new patch, and updated changelog.
N/A

v1.2.1 patch

---

Basic/DynamicAddressablesNetworkPrefabs/README.md

Adding some background on addressables, not all users are familiar with them.
Ideally this should be merge to develop soon, so that users clicking this can have that background asap.

Some background on addressables

---

Basic/2DSpaceShooter/README.md
Basic/ClientDriven/README.md
Basic/DynamicAddressablesNetworkPrefabs/README.md
Basic/Invaders/README.md
README.md

Quick updates to bitesize samples' readme in anticipation of v1.3.0 release.
N/A
- [ N/A ] Pull request has a meaningful description of its purpose
- [ N/A ] All commits are accompanied by meaningful commit messages

chore: readme updates for v1.3.0 release

---

Basic/2DSpaceShooter/ProjectSettings/ProjectSettings.asset
Basic/ClientDriven/ProjectSettings/ProjectSettings.asset
Basic/DynamicAddressablesNetworkPrefabs/ProjectSettings/ProjectSettings.asset
Basic/Invaders/ProjectSettings/ProjectSettings.asset
CHANGELOG.md
README.md

PR to update README, CHANGELOG and project versions with 1.4.0 release.
N/A

chore: project versions updated and changelog updated with 1.4.0 release

---

Basic/ClientDriven/Assets/Prefabs/Ingredient.prefab
Basic/ClientDriven/Assets/Prefabs/PlayerArmature_Networked.prefab
Basic/ClientDriven/Assets/Scenes/Bootstrap.unity
Basic/ClientDriven/Assets/Scripts/DebugSimulationSlider.cs
Basic/ClientDriven/Assets/Scripts/ServerIngredient.cs
Basic/ClientDriven/Assets/Scripts/ServerPlayerMove.cs

Just re-enabling ingredient spawner

Fix: re-enabling ingredient spawner

---

Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs
CHANGELOG.md

This is an internal PR that brings along the fix completed in this external PR.
Yamato jobs won't trigger from external PRs, so this is a temporary solution to ensure jobs run on external work.
N/A. Original PR: https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/pull/138

fix: fix the no fire sound problem (external PR #138)

---

Basic/2DSpaceShooter/Packages/manifest.json
Basic/2DSpaceShooter/Packages/packages-lock.json
Basic/ClientDriven/Packages/manifest.json
Basic/ClientDriven/Packages/packages-lock.json
Basic/Invaders/Packages/manifest.json
Basic/Invaders/Packages/packages-lock.json
CHANGELOG.md
Experimental/MultiplayerUseCases/Packages/manifest.json
Experimental/MultiplayerUseCases/Packages/packages-lock.json

Quick PR to upgrade the version used across all bitesize samples for Utilities package to v.1.8.0.
N/A

feat: Updating utilities package for samples to v1.8.0

---

CHANGELOG.md
Experimental/MultiplayerUseCases/Packages/manifest.json
Experimental/MultiplayerUseCases/Packages/packages-lock.json
Experimental/MultiplayerUseCases/ProjectSettings/ProjectVersion.txt

Upgraded Multiplayer Use Cases to the latest LTS (2022.3.27f1).
Run the project locally with a host and a client to make sure the game loop is still working without any errors.
[MTT-8501](https://jira.unity3d.com/browse/MTT-8501)

Upgrade Multiplayer Use Cases to Unity Editor 2022.3.27f1 [MTT-8501]

---

Basic/ClientDriven/Packages/manifest.json
Basic/ClientDriven/Packages/packages-lock.json
Basic/ClientDriven/ProjectSettings/ProjectVersion.txt
CHANGELOG.md

Upgrading Client Driven to Unity 2022.3.27f1 LTS.
To test: 
Connect as a host. 
Connect a client to host.
Verify visual and gameplay elements function as normal.
[MTT-8512](https://jira.unity3d.com/browse/MTT-8512)

feat: Client Driven project upgraded to 2022.3.27f1 LTS [MTT-8512]

---

Experimental/MultiplayerUseCases/Assets/Common/Scripts/GameUI.cs
Experimental/MultiplayerUseCases/Assets/UseCaseSamples/NetvarVsRpc/Scripts/ColorManager.cs
Experimental/MultiplayerUseCases/Assets/UseCaseSamples/NetvarVsRpc/Scripts/ProximityTrigger.cs
Experimental/MultiplayerUseCases/Assets/UseCaseSamples/NetworkVariables/Scripts/CharacterManager.cs
Experimental/MultiplayerUseCases/Assets/UseCaseSamples/ProximityChecks/Scripts/ColorManager.cs
Experimental/MultiplayerUseCases/Assets/UseCaseSamples/RPCs/Scripts/MoodManager.cs
Experimental/MultiplayerUseCases/Packages/manifest.json
Experimental/MultiplayerUseCases/Packages/packages-lock.json
Experimental/MultiplayerUseCases/README.md

PR for upgrading NGO to package V1.8.1. This includes adjusting scripts for implementing new API.
Includes:
- New RPC attributes
- OnConnectionEvent
Validation: 
Check if scenes work as expected.
[MTT-8499](https://jira.unity3d.com/browse/MTT-8499)

Upgrade Multiplayer Use cases to NGO 1.8.1 [MTT-8499]

---

Experimental/DistributedAuthoritySample/Assets/Prefabs/Gameplay/PlayerSpawnPoints.prefab
Experimental/DistributedAuthoritySample/Assets/Prefabs/Gameplay/PlayerSpawnPoints.prefab.meta
Experimental/DistributedAuthoritySample/Assets/Scripts/Gameplay/PlayerSpawnPoints.cs
Experimental/DistributedAuthoritySample/Assets/Scripts/Gameplay/PlayerSpawnPoints.cs.meta
Experimental/DistributedAuthoritySample/Assets/Scripts/Player/AvatarTransform.cs

feat: Distributed Authority Sample - player spawn points [MTT-8899]

---

Experimental/DistributedAuthoritySample/Assets/Prefabs/Characters/Avatar.prefab
Experimental/DistributedAuthoritySample/Assets/Scripts/GameManagement/GameplayEventHandler.cs
Experimental/DistributedAuthoritySample/Assets/Scripts/Input/AvatarInputs.cs
Experimental/DistributedAuthoritySample/Assets/Scripts/Player/AvatarTransform.cs
Experimental/DistributedAuthoritySample/Assets/Scripts/Services/ServicesHelper.cs
Experimental/DistributedAuthoritySample/Assets/Scripts/UI/HomeScreenView.cs

Quick PR to fix a few things noticed on a playtest.
This PR fixes:
* Player names not being displayed
* Session reconnection not working
* Interact action being disabled after a player disconnects
* Mouse being locked -> unable to click on in-game window button to go back to main menu
N/A

fix: Distributed Authority Sample - fixes to player name, session reconnection, input actions being disabled, mouse unlocked

---

.yamato/project.metafile
Experimental/DistributedAuthoritySample/Packages/manifest.json
Experimental/DistributedAuthoritySample/Packages/packages-lock.json
Experimental/DistributedAuthoritySample/ProjectSettings/ProjectVersion.txt
Experimental/DistributedAuthoritySample/ProjectSettings/VirtualProjectsConfig.json

Upgrade to LTS version & MPPM upgraded.
MPPM upgrade resolves the `Player x Failed to Sync` issue where clones would not open properly.
N/A

feat: Distributed Authority Sample - 6000.0.24f1 LTS upgrade, MPPM upgraded

---

Experimental/Anticipation Sample/Assets/Scenes/SampleScene.unity

This resolves the issue with the U6 upgrade of the Anticipation Sample.
[MTTB-887](https://jira.unity3d.com/browse/MTTB-887)

fix: upgrade artifact issue with anticipated sample
